# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'GasMoney' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GasMoney
	pod 'Firebase/Database'
	pod 'Firebase/Auth'
	pod 'Firebase/Analytics'
	pod 'NVActivityIndicatorView'
	pod 'NotificationBannerSwift'

end
